name: PR Source Check

on:
  pull_request:
    branches: [prod]

jobs:
  check-pr-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source
        run: |
          if [ "${{ github.base_ref }}" = "prod" ] && [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Error: PRs to prod must come from the dev branch"
            echo "Current PR is from ${{ github.head_ref }} to ${{ github.base_ref }}"
            exit 1
          else
            echo "PR source check passed"
          fi